### PR TITLE
Background mode

### PR DESCRIPTION
**Pull request by dugamarian**
Certainly, there is room for improvement, but now the application is functional (I only tested with LLU online mode, needs further testing with Bluetooth connection), It sends values to the calendar minute by minute and updates live activities on the lock screen. 

The background mode was implemented with the help of this tutorial: https://medium.com/@pietromessineo/refresh-live-activities-in-background-every-second-is-possible-a9fecf34783a.

### CODE REVIEW

**Comment by gui-dos** [comment]
As I requested to @AnubhavRawat02 in #4, could you please use `DiaBLE.xcconfig` as configuration base (https://github.com/gui-dos/DiaBLE/commit/ff3ee941aa7f617ba7f0991a366cccbd1bb88bc3) instead of your explicit `DEVELOPMENT_TEAM` and simply "Widgets" as the Xcode Widget Extension target name, putting all the new files in a subfolder and adjusting the _WidgetsExtension.entitlements_ and _Info.plist_’s paths to point to them (d39afe6)?

**Comment by dugamarian** [comment]
Yes, but have you tested this build?

**Comment by gui-dos** [comment]
No, I am not going to use this workaround to play empty sounds. xDrip4iOS is already doing it and there are certainly much more better solutions ;-)

**Comment by dugamarian** [comment]
> Until then, the main app is not useful unfortunately. I asked if you test it, not if you use it.  Here’s a screenshot of what is right now. 

[Diable .pdf](https://github.com/gui-dos/DiaBLE/files/13400306/Diable.pdf)

**Pull request closed without merging**
