### PR TITLE
chore: adjust glucose limits

### PR DESCRIPTION
**Pull request by 3djc**
Match 'normal' glucose range of 80-120

### CODE REVIEW

**Comment by gui-dos** [comment]
This is not a medical recommendation but a mere UI choice: 99 is just the maximum 2-digit number that doesn’t make the labels move :-)

SwiftUI doesn’t let you customize easily like in UIKit the colors of both the left and the right segments of a slider since there is no `SliderStyle`: a more ideal solution would be to use a single slider with four thumbs, the center target range colored in green and red alarms thresholds at the margins but without wrapping an `UISlider` in a `UIViewRepresentable`. 

I am optimizing the SettingsView to be controlled comfortably at the thumb’s reach, without needing to scroll it: in smaller displays thumbs cannot be accurate so I am leaving some leeway purposely.

**Comment by 3djc** [comment]
Ok for 99, but why start at 140 lowest then (my alarms are set at 75/130 :) )

**Comment by gui-dos** [comment]
OK. 239cd0a lowers to 120 the `targetHigh` / `alarmHigh` sliders low ends.

Since our Vendor is targeting also athletes with the Biosensors and supporting all those “metabolic health” startups (I was contacted already by a dozen of them), let’s support them, too ;-)

**Comment by 3djc** [comment]
Works for me !

**Pull request closed without merging**
